[project]
name = "compem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "seiHU06", email = "r.god.510@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [ "ipykernel>=6.0", "japanize-matplotlib>=1.1.3", "jupyterlab>=4.0", 
"matplotlib>=3.7", "numpy>=1.24", "pandas>=2.0", "scikit-learn>=1.3", "seaborn>=0.13", "statsmodels>=0.14", ]


[project.scripts]
compem = "compem:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
